# Generated by Django 5.1.5 on 2025-05-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app_kurs', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
